-   id: flakehell
    name: flakehell
    description: '`flakehell` is a `flake8` wrapper to make a nice, legacy-friendly, configurable command-line utility for enforcing style consistency across Python projects.'
    entry: flakehell lint
    language: python
    language_version: python3
    types: [python, markdown, rst, jupyter, yaml]
    require_serial: true
